boot.o: boot.S multiboot.h x86_desc.h types.h
idtas.o: idtas.S
interrupt.o: interrupt.S
x86_desc.o: x86_desc.S x86_desc.h types.h
file_system.o: file_system.c lib.h types.h file_system.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c x86_desc.h types.h lib.h keyboard.h i8259.h interrupt.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h page.h file_system.h
keyboard.o: keyboard.c keyboard.h i8259.h types.h lib.h terminal.h
lib.o: lib.c lib.h types.h
page.o: page.c page.h types.h
rtc.o: rtc.c rtc.h i8259.h types.h lib.h
terminal.o: terminal.c terminal.h lib.h types.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h
